# Description
title = "Pynasonde"
author = "S. Chakraborty"

# Table for auto-scaler
[ngi]
scaler.noise_constant=2
scaler.frequency_min=0
scaler.frequency_max=15
scaler.height_min=50
scaler.height_max=400
scaler.mode="O"
scaler.dbscan.eps=15
scaler.dbscan.min_samples=100
scaler.otsu.nbins=1000
scaler.otsu.thresh=2
scaler.segmentation_method="k-means"
scaler.apply_filter=true

[polan]
h_max_simulation=500
h_step=1e-3

[vipir_data_format_maps]
version=1.0
[[vipir_data_format_maps.configs]]
vipir_version=1
data_type=2
np_format="float32"
[[vipir_data_format_maps.configs]]
vipir_version=0
data_type=1
np_format="float32"